#################################
# Crypt - example configuration #
#################################

# These are example definition of Crypt services.
# In order to use them, you first must call Crypt::setConfig($pathToYourConfig),
# and then just use the CryptTrait (eg. $this->crypt('Password'))
# If you don't want to use Crypt as a service, you can use the constructor
# new Crypt($passwordAlgo, $cipherMode, $cipherBlock, $cipherInitVector)
Crypt:
    # You can overwrite the default driver by providing your own.
    # How to create a new driver, read in the Readme.md file.
    # If you don't wish to change the default driver,
    # just ommit this definition in your config file.
    Bridge: \Webiny\Component\Crypt\Bridge\Webiny\Crypt
